### ISSUE TITLE
Approve/rejekt for references is missing

### ISSUE THREAD

**Issue by Crazy1880** [google/primarysources#70]
Since yesterday afternoon, the buttons for approve or reject are missing for the parameter of references. Its in all items with a reference like URL. Other parameter are still ok. See picture
![approve-rejekt is missing for references](https://cloud.githubusercontent.com/assets/14944867/12317250/b02374cc-ba8f-11e5-8834-90a82b6c672d.JPG)

**Comment by marfox** [comment]
+1

**Comment by Crazy1880** [comment]
@Tpt , @wastl : Is there any information for fixing this issue?

**Comment by tomayac** [comment]
Seems like a recent CSS update in Wikidata broke this part. Changing…

```css
.wikibase-referenceview .wikibase-referenceview-heading {
  min-height: 1.5em;
  padding: 5px;
  background-color: #F0F0F0;
  display: none;
}
```

…to…

```css
.wikibase-referenceview .wikibase-referenceview-heading {
  min-height: 1.5em;
  padding: 5px;
  background-color: #F0F0F0;
  display: block;
}
```

…fixes the issue. @lydiapintscher, can you or someone from your team fix this? The deep link to the CSS in question is [long](https://www.wikidata.org/w/load.php?debug=false&lang=en&modules=ext.echo.badgeicons%7Cext.echo.styles.badge%7Cext.gadget.AuthorityControl%2CCommonsMedia%2CNewSection%2CPopupsFix%2CPrimarySources%2CProtectionIndicators%2CSearch%2CSiteIdToInterwiki%2Cimagelinks%7Cext.math.desktop.styles%7Cext.math.scripts%2Cstyles%7Cext.tmh.thumbnail.styles%7Cext.uls.nojs%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikidata-org.badges%7Cext.wikimediaBadges%7Cjquery.wikibase.statementview.RankSelector.styles%7Cjquery.wikibase.toolbar.styles%7Cjquery.wikibase.toolbarbutton.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.sectionAnchor%7Cmediawiki.skinning.interface%7Cskins.vector.styles%7Cwikibase.common&only=styles&skin=vector) and may be personalized to my settings, I don't know…

**Comment by thiemowmde** [comment]
We streamlined the layout in December 2015 (see https://gerrit.wikimedia.org/r/254140) and made this gray heading bar invisible in non-edit mode. By default it's empty and does not help making the page more readable. It reappears in edit-mode because we need it ourself for our toolbar buttons.

Other tools had the same issue as you and solved it by enforcing the visibility of this heading container with a slightly more specific CSS selector. See https://www.wikidata.org/w/index.php?title=MediaWiki:Gadget-DuplicateReferences.css&oldid=296214700.

I talked to @lydiapintscher and we do not want to make these gray bars visible again by default. Please apply the same patch as the gadget linked above.

**Comment by tfmorris** [comment]
So this needs to be reopened. I've inlined the patch below:
```css
/**
 * Adds a link to copy references and add them to other statements on the same item.
 *
 * @see [[MediaWiki:Gadget-DuplicateReferences.js]]
 * @author Bene*
 */

/* show reference heading which is otherwise only visible in edit mode */
.wikibase-referenceview div.wikibase-referenceview-heading {
	display: block;
}
```
